"use client";

import { Shield } from "lucide-react";

export default function PrivacyPage() {
  return (
    <main>
      <div className="container mx-auto px-4 py-16">
        <div className="mb-8 text-center">
          <div className="flex justify-center mb-4">
            <Shield className="h-12 w-12 text-primary" />
          </div>
          <h1 className="text-4xl font-bold tracking-tight mb-2">Privacy Policy</h1>
          <p className="text-muted-foreground">Last updated: May 25, 2022</p>
        </div>

        <div className="max-w-4xl mx-auto bg-card rounded-xl ">
            <div className="prose prose-gray dark:prose-invert max-w-none">
              <p className="text-muted-foreground">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
              </p>

              <p className="text-muted-foreground mt-4">
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
              </p>

              <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>
              
              <h3 className="text-xl font-medium mb-3">1.1 Interpretation</h3>
              <p className="text-muted-foreground">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
              </p>

              <h3 className="text-xl font-medium mt-6 mb-3">1.2 Definitions</h3>
              <div className="space-y-4">
                {[
                  { term: "Account", def: "A unique account created for You to access our Service or parts of our Service." },
                  { term: "Company", def: "Refers to b-lab." },
                  { term: "Cookies", def: "Small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses." },
                  { term: "Country", def: "Refers to: Vietnam" },
                  { term: "Device", def: "Any device that can access the Service such as a computer, a cellphone or a digital tablet." },
                  { term: "Personal Data", def: "Any information that relates to an identified or identifiable individual." },
                  { term: "Service", def: "Refers to the Website." },
                  { term: "Service Provider", def: "Any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used." },
                  { term: "Usage Data", def: "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." },
                  { term: "Website", def: "Refers to b-lab, accessible from www.b-lab.app" },
                  { term: "You", def: "The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." }
                ].map(({ term, def }) => (
                  <div key={term} className="pl-4 border-l-2 border-primary/20">
                    <dt className="font-medium text-primary">{term}</dt>
                    <dd className="text-muted-foreground">{def}</dd>
                  </div>
                ))}
              </div>

              <h2 className="text-2xl font-semibold mt-8 mb-4">Collecting and Using Your Personal Data</h2>
              
              <h3 className="text-xl font-medium mb-3">Types of Data Collected</h3>
              <div className="space-y-6">
                <div>
                  <h4 className="text-lg font-medium mb-2">Personal Data</h4>
                  <p className="text-muted-foreground">
                    While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                  </p>
                  <ul className="list-disc list-inside mt-2 text-muted-foreground">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Usage Data</li>
                  </ul>
                </div>

                <div>
                  <h4 className="text-lg font-medium mb-2">Usage Data</h4>
                  <p className="text-muted-foreground">
                    Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                  </p>
                </div>
              </div>

              <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
              <p className="text-muted-foreground">
                If you have any questions about this Privacy Policy, You can contact us:
              </p>
              <p className="mt-2">
                <a href="mailto:support@b-lab.app" className="text-primary hover:underline">
                  support@b-lab.app
                </a>
              </p>
            </div>
        </div>
      </div>
    </main>
  );
}